### ISSUE TITLE
Things to fix from initially shared file

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/MICrONS-to-nwb#4]
Leaving a list of items to adjust from the first draft file shared

- [x]  Pupil tracking, eye tracking, and treadmill velocity all have negative timestamps - ~~I'd usually say it's best to align the session start time with the earliest timestamp in the file (currently seems aligned to the visual stimulus timestamps which are also sync'd with the timestamps for the ROI responses?) to avoid confusion~~ EDIT: After discussion, people should be using the processed versions of this anyway so raw data is just for provenance. Fine to keep this way probably
- [x] First 20 values (of both data and timestamps) of the treadmill velocity are NaN - feel free to clip those out (other files may have different # of NaN's, or none at all)
- [x] Similarly, for pupil and eye tracking, the data (but not the timestamps) start off as NaN's; no reason to include these at the start, feel free to clip and start the series at the first non-NaN value
- [x] Would love to get a reference frame for the eye tracking
- [x] Would like units on the treadmill velocity (in distance over time)
- [x] Would also love units on the pupil and eye tracking (though this could maybe be judged from the scale of the data range relative to the subject species)
- [x] ~~units on origin_coords for imaging planes is in meters but based on values I'm guessing should be micrometers or less?~~ EDIT: schema hard codes as meters
- [x] The first ImagingPlane and ROIResponseSeries in each group does not start with an integer index on the end; for consistency, I'd recommend adding that
- [x] Also the ROIResponseSeries and plane segmentations seem to count from 1-based index whereas the ImagingPlanes seem to start from 0-based index. I'd pick one to be consistent (preference for 0-based but doesn't really matter)

Otherwise looking really good so far

**Comment by weiglszonja** [comment]
> Pupil tracking, eye tracking, and treadmill velocity all have negative timestamps - I'd usually say it's best to align the session start time with the earliest timestamp in the file (currently seems aligned to the visual stimulus timestamps which are also sync'd with the timestamps for the ROI responses?) to avoid confusion

We are currently using the "raw" data for them, however they also have them synchronised with field 1 frame times (and low-pass filtered). Can we use those tables instead of raw? The stimulus timestamps are also aligned to those same frame times.

**Comment by CodyCBakerPhD** [comment]
> We are currently using the "raw" data for them, however they also have them synchronised with field 1 frame times (and low-pass filtered).

Sorry, can you clarify? Are the raw data timestamps for pupil, eye, and treadmill 'synchronized' with the other data in the file in the sense that they are all currently within the same time basis? My point was that the relative start time of all time references in the file was not itself shifted to be the earliest time stamp.

If there are additional processed forms of that data that they also have available, such as filtered, then yes we might as well include it. When you say the processed data is 'synchronized', do you just mean they just clipped off all the time before the recording started?

**Comment by weiglszonja** [comment]
> When you say the processed data is 'synchronized', do you just mean they just clipped off all the time before the recording started?

I have to verify that from the actual data, I saw this in the [technical documentation ](https://bossdb-open-data.s3.amazonaws.com/iarpa_microns/minnie/functional_data/functional_data_technical_documentation_v3.pdf) for instance :

> 2.5 ManualPupil
> Traces from RawManualPupil were low-pass filtered with a hamming window to the scan frame rate and linearly interpolated to field 1 scan frame times.

**Comment by CodyCBakerPhD** [comment]
All good now - thanks for all the hard work @weiglszonja!
